version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hive-pushdown-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f0b7okmyy4lz"
s3_prefix = "hive-pushdown-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "LambdaFunctionName=\"hive-pushdown-lambda\" DefaultConnectionString=\"hive://jdbc:hive2://3.86.109.184:10000/default;${athena_jdbc_hortonworks_hive_test}\" SecretNamePrefix=\"athena_jdbc_hortonworks_hive_test\" SpillBucket=\"trianz-snowflake-athena-jdbc\" SpillPrefix=\"athena-spill\" LambdaTimeout=\"900\" LambdaMemory=\"3008\" DisableSpillEncryption=\"false\" SecurityGroupIds=\"sg-0398b41444bcbb0ee\" SubnetIds=\"subnet-01743fd8cca039a9e\" PermissionsBoundaryARN=\"\""
image_repositories = []
